---

- name: spin_subnets - Create Subnet ({{ subnet.name }} - {{ subnet.cidr }})
  shell: maas admin subnets create name="{{ subnet.name }}" cidr={{ subnet.cidr }} vid={{ subnet.vlan_id }} fabric={{ subnet.fabric }}
  ignore_errors: yes

- include: dhcp_on.yml
  when: subnet.dhcp_on is defined and subnet.dhcp_on
