---
- name: fail if users variable not found
  fail:
    msg: "|
        You have to define a users variable. Example:
        users:
          - name: John Doe
            username: jdoe
            key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC...
            "
  when: 'users is undefined'

- name: for each user include create_user.yml
  include: create_user.yml
  with_items: "{{ users }}"
  loop_control:
    loop_var: 'user'