---

lxd_action: none

authorized_user: "{{ hostvars[groups['metal-manual'][0]]['regular_user_pubkey'] | default(False) }}"

# TODO: Make some sort of Netplan generator...
#
# At least, for LXD, the interface names are predictable (eth0, eth1, eth2...),
# based on LXD Profile.
dns_servers: "8.8.8.8, 1.1.1.1"
dns_search: tcmc.com

containers:

- name: "vmare-{{ controller_sequence }}"
  lxd_profile: default
  ip: "172.31.242.10/24"
  gw: "172.31.242.1"

- name: "vmara-{{ controller_sequence }}"
  lxd_profile: maas_rack
  ip: "172.31.242.250/24"
  gw: "172.31.242.1"
  ip_ipmi: "172.31.240.250/24"
  ip_pxe: "172.31.243.250/24"

## Ceph Containers
#- name: vcmons-1
#  ip: "172.31.244.11/24"
#  gw: "172.31.244.1"
#
#- name: vcmgrs-1
#  ip: "172.31.244.12/24"
#  gw: "172.31.244.1"
#
#- name: vcrgws-1
#  ip: "172.31.244.13/24"
#  gw: "172.31.244.1"
#
#- name: vcmdss-1
#  ip: "172.31.244.14/24"
#  gw: "172.31.244.1"
#
#- name: vcnfsg-1
#  ip: "172.31.244.15/24"
#  gw: "172.31.244.1"
#
## Ceph iSCSI (Experimental)
##- name: vciscs-1
##  ip: "172.31.244.16/24"
##  gw: "172.31.244.1"
#
#- name: vcosd-1
#  ip: "172.31.244.21/24"
#  gw: "172.31.244.1"
#  ceph_pvt: "172.31.245.11/24"
#
#- name: vcosd-2
#  ip: "172.31.244.22/24"
#  gw: "172.31.244.1"
#  ceph_pvt: "172.31.245.11/24"
#
#- name: vcosd-3
#  ip: "172.31.244.23/24"
#  gw: "172.31.244.1"
#  ceph_pvt: "172.31.245.11/24"

# Extra Examples:

# Privileged:
#
#- name: ultra-{{ controller_sequence }}
#  privigeled: no
#  type:
#    machine: container
#    type: lxd
#  devices:
#    driver: kernel
#    ethernets:
#    - name: eth0
#      mtu: 1500
#      subnet:
#        ipv4: 172.31.242.250/24
#        gate4: 172.31.242.1

# More similar with Netplan (Experimental)
#
#- name: micro-{{ controller_sequence }}
#  devices:
#    ethernets:
#    - name: eth0
#      mtu: 1500
#      subnet:
#        addresses: 172.31.242.250/24
#        gateway4: 172.31.242.1
#      nameservers:
#        addresses: "8.8.8.8 1.1.1.1"
#        search: tcmc.com
