---
# tasks file for es
#
- name: include pre-flight check
  include: pre_flight.yml

- name: include tune.yml
  include: tune.yml

- name: include data.yml (prepare data drive)
  include: data.yml

- name: include elasticsearch.yml
  include: elasticsearch.yml
