---

- name: main - Apt install isc-dhcp-server
  apt:
    name: isc-dhcp-server
    state: present 

- name: main - Applying isc-dhcp-server config file
  template: 
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: restart isc-dhcp-server

- name: main - Make sure isc-dhcp-server is running
  systemd:
    state: started
    name: isc-dhcp-server
