---

- name: profile - Creating LXD default storage pool
  shell: lxd init --storage-backend dir --auto


- name: profile - Updating the LXD default profile
  lxd_profile:
    name: default
    description: Default LXD profile
    devices:
      eth0:
        name: eth0
        nictype: bridged
        parent: br-bond0
        type: nic
      root:
        path: /
        pool: default
        type: disk
