---

- name: Getting system user's public SSH key
  set_fact:
    authorized_user: "{{ hostvars[groups['all'][0]]['regular_user_pubkey'] | default(False) }}"


- name: "LXD - Create and start MaaS Region Controller container"
  lxd_container:
    name: vumreg-1
    state: started
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases
      protocol: simplestreams
      alias: bionic/amd64
    config:
      user.network-config: |
              # cloud-config
              version: 2
              ethernets:
                  eth0:
                      mtu: 1500
                      addresses: []
              vlans:
                  eth0.7:
                      mtu: 1500
                      id: 7
                      link: eth0
                      addresses:
                      - 172.16.34.1/24
                      gateway4: 172.16.34.254
                      nameservers:
                          addresses: [ 8.8.8.8, 8.8.4.4 ]
                          search: [ tcmc.com ]
      user.vendor-data: |
              #cloud-config
              users:
                - name: ubuntu
                  ssh_authorized_keys:
                  - {{ authorized_user }}
                  shell: /bin/bash
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
              packages:
                - python
    profiles: ["default"]
    wait_for_ipv4_addresses: true

- name: "LXD - Create and start MaaS Rack Controller container"
  lxd_container:
    name: vumrck-1
    state: started
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases
      protocol: simplestreams
      alias: bionic/amd64
    config:
      user.network-config: |
              # cloud-config
              version: 2
              ethernets:
                  eth0:
                      mtu: 1500
                      addresses:
                      - 172.16.35.1/24
              vlans:
                  eth0.7:
                      mtu: 1500
                      id: 7
                      link: eth0
                      addresses:
                      - 172.16.34.250/24
                      gateway4: 172.16.34.254
                      nameservers:
                          addresses: [ 8.8.8.8, 8.8.4.4 ]
                          search: [ tcmc.com ]
      user.vendor-data: |
              #cloud-config
              users:
                - name: ubuntu
                  ssh_authorized_keys:
                  - {{ authorized_user }}
                  shell: /bin/bash
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
              packages:
                - python
    profiles: ["default"]
    wait_for_ipv4_addresses: true
