---

- name: "container - LXD - Create and start MaaS Region Controller container"
  lxd_container:
    name: vumreg-1
    state: started
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases
      protocol: simplestreams
      alias: bionic/amd64
    config:
      user.network-config: "{{ lookup('template', 'maas-region-netplan.j2') }}"
      user.vendor-data: "{{ lookup('template', 'user-data.j2') }}"
    profiles: ["default"]
    wait_for_ipv4_addresses: true

- name: "container - LXD - Create and start MaaS Rack Controller container"
  lxd_container:
    name: vumrck-1
    state: started
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases
      protocol: simplestreams
      alias: bionic/amd64
    config:
      user.network-config: "{{ lookup('template', 'maas-rack-netplan.j2') }}"
      user.vendor-data: "{{ lookup('template', 'user-data.j2') }}"
    profiles: ["default"]
    wait_for_ipv4_addresses: true
