---
# Copyright 2018, TCMC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: empty_qcow2c - Set fact disk_destination {{ disk.name }}.{{ disk.driver.type }}c ({{ vm.name }})
  set_fact:
    disk_destination: "{{ libvirt_pool_1 }}/{{ disk.name }}.{{ disk.driver.type }}"


- name: empty_qcow2c - Check if {{ disk_destination }} already exists
  stat:
    path: "{{ disk_destination }}"
  register: disk_existance


- name: empty_qcow2c - Create {{ disk_destination }}c Compressed QCoW2 ({{ vm.name }})
  shell: |
    qemu-img create -f "{{ disk.driver.type }}" "{{ disk_destination }}" "{{ disk.size }}G"
    qemu-img convert -c -f "{{ disk.driver.type }}" -O "{{ disk.driver.type }}" "{{ disk_destination }}" "{{ disk_destination }}c"
  when: not disk_existance.stat.exists

- name: empty_qcow2c - Remove old file
  file:
    path: "{{ disk_destination }}"
    state: absent
  when: not disk_existance.stat.exists


- name: empty_qcow2c - Set file permissions for {{ disk_destination }}c ({{ vm.name }})
  file:
    path: "{{ disk_destination }}c"
    owner: libvirt-qemu
    group: kvm
    mode: 0640
