---
# tasks file for logstash
- name: install java
  apt:
    name: default-jdk 

- name: Add Elasticsearch apt key
  apt_key:
   url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
   state: present

# Add the Elasticsearch apt repo. For versions 6 of the stack - use '6.x-prerelease':

- name: Adding Elasticsearch repo
  apt_repository:
   repo: deb https://artifacts.elastic.co/packages/{{ es_version }}/apt stable main
   state: present

# Installing Logstash

- name: Install Logstash
  apt:
   name: logstash
   update_cache: yes

- name: render input template
  template: 
    src: 02-beats-input.conf.j2
    dest: /etc/logstash/conf.d/02-beats-input.conf
  notify: restart logstash

- name: render filter template
  template:
    src: 10-syslog-filter.conf.j2
    dest: /etc/logstash/conf.d/10-syslog-filter.conf
  notify: restart logstash

- name: render output template
  template:
    src: 30-elasticsearch-output.conf.j2
    dest: /etc/logstash/conf.d/30-elasticsearch-output.conf
  notify: restart logstash
